# Generated by Django 4.2.6 on 2023-11-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistentes',
            fields=[
                ('id_asistente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=145, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=145, null=True)),
                ('fono', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(blank=True, max_length=245, null=True)),
                ('credenciales', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'asistentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atenciones',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=280, null=True)),
                ('tratamiento', models.CharField(blank=True, max_length=280, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=245, null=True)),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atenciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=10, null=True)),
                ('nombres', models.CharField(blank=True, max_length=145, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=145, null=True)),
                ('fono_1', models.CharField(blank=True, max_length=14, null=True)),
                ('fono_2', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(blank=True, max_length=245, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichasClinicas',
            fields=[
                ('id_ficha_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fichas_clinicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=145, null=True)),
                ('num_chip', models.CharField(blank=True, max_length=145, null=True)),
                ('edad_meses', models.IntegerField(blank=True, null=True)),
                ('sexo', models.IntegerField(blank=True, null=True)),
                ('url_imagen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Razas',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_raza', models.CharField(blank=True, max_length=85, null=True)),
                ('nombre_especie', models.CharField(blank=True, max_length=85, null=True)),
            ],
            options={
                'db_table': 'razas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinarios',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=145, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=145, null=True)),
                ('credenciales', models.CharField(blank=True, max_length=145, null=True)),
                ('fono', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(blank=True, max_length=245, null=True)),
            ],
            options={
                'db_table': 'veterinarios',
                'managed': False,
            },
        ),
    ]
