# Generated by Django 4.2.5 on 2023-11-22 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_atencion_cliente_mascota_raza_tipousuario_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mascota',
            new_name='Ficha_clinica',
        ),
    ]
