# Generated by Django 4.2.5 on 2023-11-23 01:41

from django.db import migrations, models
import veterinaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_rename_mascota_ficha_clinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_clinica',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='ficha_clinica',
            name='imagen',
            field=models.ImageField(default='mascotas/mascota.png', null=True, upload_to=veterinaria.models.Ficha_clinica.generarRuta),
        ),
    ]
