# Generated by Django 4.2.5 on 2023-11-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
