# Generated by Django 4.2.5 on 2023-11-23 22:58

from django.db import migrations, models
import django.db.models.deletion
import veterinaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0009_customuser_id_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=95)),
                ('num_chip', models.CharField(max_length=145, null=True)),
                ('edad_meses', models.IntegerField(null=True)),
                ('sexo', models.BooleanField(null=True)),
                ('imagen', models.ImageField(default='mascotas/mascota.png', null=True, upload_to=veterinaria.models.FichaClinica.generarRuta)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinaria.cliente')),
                ('id_raza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinaria.raza')),
            ],
        ),
        migrations.AlterField(
            model_name='atencion',
            name='id_mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinaria.fichaclinica'),
        ),
        migrations.DeleteModel(
            name='Ficha_clinica',
        ),
    ]
