# Generated by Django 4.2.5 on 2023-12-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
